name: Running check assistance
on:
  schedule: 
    - cron: '20 * * * *'
  workflow_dispatch:
jobs:
  Test:
    runs-on: macos-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change the Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run
        
